### ISSUE TITLE
What is the eigenvalues of FLAME2020 model 

### ISSUE THREAD

**Issue by Easy-Shu** [Rubikplayer/flame-fitting#20]
The FLAME2020 model  only provides the principle components (PCs), but where is the corresponding eigenvalues?

**Comment by TimoBolkart** [comment]
Each FLAME shape and expression components are scaled by the standard deviation. Therefore, varying the shape and expression parameters in the range [-n, n] corresponds to a variation of [-n*sigma, n*sigma]. In order to get the eigenvalues back, reshape the shapedirs (5023 x 3 x 400) to a matrix of shape 3*5023 x 400, and get the norm of 3*5023-dimensional columns of the matrix. This norm corresponds to the standard deviation, which is the square root of the eigenvalue of the covariance matrix. Does this answer your question?

**Comment by Easy-Shu** [comment]
Thanks for your reply. I think I can calculate the covariance matrix now.
